spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: 20182018Leo!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernat:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false
#spring.jpa.open.in.view
logging:
  level:
    root: WARN
    #br.com.erudio: DEBUG